### PR TITLE
Fix for Audacity downloader

### PR DESCRIPTION
**Pull request by DanielVolz**
I hope I fixed the broken downloader. It works for me at least. Sorry if something is not right, this is my first PR and my first working Autopkg receipt 😄 .

### CODE REVIEW

**Comment by cwhits** [comment]
I'm not sure this recipe would work on future updates. It works once, but because you're ending it with an empty `re_pattern` I'm not sure it'll ever download any updates.

**Comment by timsutton** [comment]
The fix from #26 has been working for me. Is this not the case for you?

**Comment by timsutton** [comment]
..and, I didn't see #28 until now. Let's try that first..

**Comment by timsutton** [comment]
Looks like #28 does it for me. I think that's the better solution, but thanks for submitting this anyway!

**Comment by DanielVolz** [comment]
@cwhits the old (the commit from 6 days ago) receipt tried to download it from a wrong url for my, that's why I tried to make my own. 

Unfortunately I'm not very skilled with autopkg receipts and I didn't really understand completely how the sees her processor works. 

Like I understand it, the first urlsearcher processor visits the audacity site with the download links.. The second visits the site/link found by the first processor and looks for the generated/true download link and the third processor saves the link to the url key so that the downloader can download it? 

But maybe you can tell me how it really works ;)

@timsutton thanks for all of your tool! I really love them and use them in my part-time admin job.

**Pull request closed without merging**
