### PR TITLE
Update Ableton recipe

### PR DESCRIPTION
**Pull request by apizz**
A number of updates to resume and enhance recipe functionality

### CODE REVIEW

**Comment by apizz** [comment]
When I revisited this originally v9 was on 9.7.5 and 9.7.6 is current so it would appear patches are still coming despite the new version.

AppDmgVersioner was more to avoid having to include a second EDITION variable with upper case letter for code sign check, as it grabs the app name in addition to the version.

**Comment by apizz** [comment]
👋

**Comment by apizz** [comment]
👋

**Comment by timsutton** [comment]
Thanks @apizz. Just looking in on PRs after being mostly off GitHub the past couple years.

**Pull request merged**
